### ISSUE TITLE
Relative path CWD

### ISSUE THREAD

**Issue by alexVauch** [stephenplusplus/grunt-wiredep#119]
Hi there!
I have an issue when using relative path in CWD.

--- build (Grunt with grunt-bower-install)
--- src (bower.json and src files)

Don't work:
Can't find src files but handles ../src/bower.json.
```
		bowerInstall: {
			files: {
				src      : ['index.html'],
				cwd      : '../src/'
			}
		}
```

Work when src has absolute path.
```
		bowerInstall: {
			files: {
				src      : ['absolute/path/to/file/index.html'],
				cwd      : '../src/'
			}
		}
```

Thank you.

**Comment by stephenplusplus** [comment]
Try upgrading to grunt-wiredep :)

**Comment by alexVauch** [comment]
Yeah! It did the trick. Thanks!
