### ISSUE TITLE
Multiple apps in same project

### ISSUE THREAD

**Issue by sondreb** [stephenplusplus/grunt-wiredep#120]
Is it possible to have multiple apps in same project? It would be nice if it was possible to do "grunt wiredep:win" and "grunt wiredep:android", and then have two different projects with different dependencies.

**Comment by stephenplusplus** [comment]
You should be able to. grunt-wiredep can be configured with different targets, like all other grunt tasks. As far as the configuration to use, see the wiredep readme.

Going to close the issue, but feel free to post a more detailed solution when you get it working in case others interested in the same thing stop by.
