### ISSUE TITLE
bower_components folder is not created on task run

### ISSUE THREAD

**Issue by dmytro-shchurov** [stephenplusplus/grunt-wiredep#123]
I thought it is supposed that this folder must be created on a fresh copy of a project. What is the sense to have an automated task and creation of the folder manually (or with and additional task which seems weird). A configuration is
```
'bowerInstall': {
    target: {
        src: ['<%= approot %>/index.html'],
        cwd: '<%= approot %>'
    }
}
```
As a result of `$ grunt bowerInstall` I've got 
>Warning: ENOENT, no such file or directory '../www/bower_components' Use --force to continue

**Comment by stephenplusplus** [comment]
It's called `wiredep` - try installing `grunt wiredep` and use it to wire dependencies to your source files. Search the issues if you're curious the history of `bowerInstall` vs `wiredep` :)
