### ISSUE TITLE
Error creating multiple targets with two different parameter specifications 

### ISSUE THREAD

**Issue by xtianus79** [stephenplusplus/grunt-wiredep#124]
My grunt file crashes when I try to use wiredep.  

I get this error... with this configuration:
warning: Required config property "wiredep.html.src" missing. use --force  
everything on its own works great!

    wiredep: {
		    hmtl: {
		        target: {
		            src: [
                        '<%= app %>/**/*.html'
		            ],

		            ignorePath: '../',
		            exclude: [
                        'modernizr',
                        'font-awesome',
                        'jquery-placeholder',
                        'foundation'
		            ]
		        }
		    },
		    cshtml: {
		        target: {
		            src: [
                        '<%= app %>/**/*.cshtml'
		            ],

		            fileTypes: {
		                html: {
		                    block: /(([\s\t]*))(\n|\r|.)*?()/gi,
		                    detect: {
		                        js: /<script.*src=['"](.+)['"]>/gi,
		                        css: /<link.*href=['"](.+)['"]/gi
		                    },
		                    replace: {
		                        js: '<script src="~/lib{{filePath}}"></script>',
		                        css: '<link rel="stylesheet" href="~/lib{{filePath}}" />'
		                    }
		                }
		            },

		            ignorePath: '../bower_components',
		            exclude: [
                        'modernizr',
                        'font-awesome',
                        'jquery-placeholder',
                        'foundation'
		            ]
		        }
		    }

		}

**Comment by stephenplusplus** [comment]
Sorry the slow reply. Just remove the nested `target` labels for `html` and `cshtml`. (So that you get `wiredep.html.src` and not `wiredep.html.target.src`.

**Comment by xtianus79** [comment]
yes somehow or another I figured that out. thanks.
