### ISSUE TITLE
Question: Is there a way to force order of scripts?

### ISSUE THREAD

**Issue by dtracers** [stephenplusplus/grunt-wiredep#125]
I have a component that I personally made that depends on jquery but when using this plugin it is inserted above it.
Is there a way to force wiredep to order the installation in a different way?

**Comment by CWSpear** [comment]
What's your component?

`wiredep` uses the `dependencies` in a components' `bower.json`. So if you properly set `jquery` as a dependency there, `wiredep` knows that `jquery` needs to be included before it.

**Comment by dtracers** [comment]
well basically I have am doing two things.  (One of which is a little odd...)
the first one is I am modifying jquery so that the $(document).ready does not fire till after the webcomponentjs fires its events.  This is because I am using the webcomponents and I am trying to get a little backward compatibility.

The second thing I am doing (also has to deal with webcomponents) is I have to modify jquery so that it only runs once.  I am using this component to make that happen.  It basically inserts a function at the top of every library that I only want to run once.
https://github.com/dtracers/validateFirstRun

This other problem is that technically every library that uses the firstRun component has a dependency on it.  But I don't think it would be a good idea to change the bower file of jquery.  Do the overrides contain this ability?

**Comment by CWSpear** [comment]
Yes, I think so? Still a little confused as to what you're doing. But if your project needs jQuery to work, you want to list it as a dependency.

**Comment by dtracers** [comment]
So let me use code examples instead of word examples.

order wiredep is inserting code
```
jquery
validateRunOnce
myLibraryThatDependsOnJquery
```

the order I need is

```
validateRunOnce
jquery
myLibraryThatDependsOnJquery
```

**Comment by stephenplusplus** [comment]
Thank you for explaining in so many ways :) I think this is a use case we just don't want to support. It's pretty weird (no fault there; making a website is weird in general!), and the fact we haven't run into this before makes me feel comfortable with the options we give developers now.

I'm not sure this will work for your use case, but maybe using `exclude` and writing necessary script tags manually will do the trick?
