### ISSUE TITLE
Wiredep and bower components

### ISSUE THREAD

**Issue by pagoad** [stephenplusplus/grunt-wiredep#126]
Hi.
I would like to change bower_components path and add "/" before url, when wiredep put all .js files into jade template.
I tried to do this in wiredep.js but it does not work.
I would like to chenge from:
        // bower:js
        script(src='bower_components/jquery/dist/jquery.js')

to:
        // bower:js
        script(src='/bower_components/jquery/dist/jquery.js')

       fileTypes: {
          jade: {
            replace: {
              js: 'script(src=\'/{{filePath}}\')',
              css: 'link(rel=\'stylesheet\', href=\'/{{filePath}}\')'
            }
          }

It should work, but it is not.
Could you help ?

**Comment by stephenplusplus** [comment]
It worked as expected for me in testing. Can you try un- and re-installing grunt-wiredep to be sure you're using the latest wiredep?

**Comment by pagoad** [comment]
I did it, but without effect :(

**Comment by stephenplusplus** [comment]
What OS/platform are you running? Can you do a triple check that you're using the latest wiredep?

It's the worst when something works for you and not for someone else, isn't it? :cry:

**Comment by CWSpear** [comment]
This definitely should be working, but I do want to point out that I prefer the pattern of putting my relative assets in my `link` and `script` tags and then adding `<base href="/" />` to my `<head>`. 

Ya know... cuz that one time 5 years ago when I had a project put me in a subdirectory and if I had done that, all I would have had to do was update the `base` and it all would have worked, but I didn't, and I had update all the links in the entire project!

**Comment by eddiemonge** [comment]
closing since this is old and should be in other places like wiredep
