### ISSUE TITLE
How to getting minified files instead

### ISSUE THREAD

**Issue by nhuthuynh** [stephenplusplus/grunt-wiredep#130]
Hello,
first thank to grunt-wiredep, it is very helpful in development. But i have a question or request, Could i inject minified files ? i just want to inject minified files like angular.min.js or bootstrap.min.css into my html file.

**Comment by stephenplusplus** [comment]
Glad to hear it's helpful! :)

This does come up a lot, but we still think minification is the responsibility of the package consumer, and not its author. There are many great tools that will integrate alongside `grunt-wiredep` that will get the job done.
