### ISSUE TITLE
Don't require bower to be installed globally

### ISSUE THREAD

**Issue by provegard** [stephenplusplus/grunt-wiredep#131]
It would be useful to be able to specify a path to the bower binary. Right now I cannot use this plugin due to this.

**Comment by stephenplusplus** [comment]
Why?

**Comment by provegard** [comment]
Bower isn't installed globally on the CI server that builds my project, and I prefer to keep it that way. I like it better when a project can be built with as few global dependencies as possible.

**Comment by stephenplusplus** [comment]
Where does wiredep use Bower directly?

**Comment by provegard** [comment]
No idea. Maybe I've drawn the wrong conclusion? I just noticed that Grunt failed when Bower wasn't installed globally. But I'll re-check...

**Comment by provegard** [comment]
Huh, apparently I opened the issue in the wrong repository... should've been grunt-auto-install. My apologies! :-)

**Comment by stephenplusplus** [comment]
No problem, there are way too many of us!
