### ISSUE TITLE
inject bower:css with bootstrap.css

### ISSUE THREAD

**Issue by jadir-junior** [stephenplusplus/grunt-wiredep#135]
I don't able to inject bootstrap.css, other files injected normally

**Comment by dspice** [comment]
I have the same problem, it seems Bootstrap changed their bower.json to be inline with the bower spec.
There are several temp fixes listed here https://github.com/twbs/bootstrap/issues/16663 and links to the causes etc.

**Comment by cvrebert** [comment]
See https://github.com/taptapship/wiredep/issues/180

**Comment by crrollyson** [comment]
Not ideal, but I rolled back to BS version 3.3.4 and setting up like this:

`bower install --save bootstrap#3.3.4`

`bower_concat: {
 all: {
  dest: {
   'js': 'path/to/file/_bower.js',
   'css': 'path/to/file/_bower.css'
  }
 }
}`
