### ISSUE TITLE
Bootstrap 3.3.5 css import issue

### ISSUE THREAD

**Issue by kkak10** [stephenplusplus/grunt-wiredep#136]
I am not good at English.

First, I use grunt-wiredep.

bower install bootstrap, bootstrap version is 3.3.5

index.html in
 
  

  
  

and I'm execute command "grunt wiredep"

bootstrap.js is import in index.html but bootstap.css is not import in index.html

so I'm change the bootstrap version 

3.3.5 -> 3.0.0

bootsrap version change after I'm again execute command "grunt wiredep" then

bootstrap css import in index.html

thank.

ps.bootstrap 3.2 is normal import css, issue version is 3.3

**Comment by lsnascimento** [comment]
Hi, check inside the folder bootstrap the bower.json file.
Within the index "main" must be the path of the css. 
Usually it comes without the mapped css.

I hope it helps

**Comment by sunboya** [comment]
2f  is right, thx :)

**Comment by mbrig-co** [comment]
Yes thanks it also worked for me.

**Comment by eddiemonge** [comment]
its because bootstrap changed their main property. You have to add an override for it now.
