### ISSUE TITLE
Line Endings on Windows

### ISSUE THREAD

**Issue by coreyog** [stephenplusplus/grunt-wiredep#137]
On a windows machine you end up injecting using `\n` instead of `\r\n`.

When joining this plugin with other plugins, this can cause major breaking issues.

For example, I'm using yeoman to concatenate, minify, and version my javascript files, including my bower js files. Yeoman knows I'm on windows and looks for `\r\n` but currently this plugin breaks that using only `\n`.

The problem can be traced to inject-dependencies.js:89

**Comment by CWSpear** [comment]
There is no `inject-dependencies.js` in this repo. I think you meant to post this on [taptapship/wiredep](https://github.com/taptapship/wiredep) (the module that this plugin uses).

But going over there, there's nothing about line ending on [inject-dependencies.js:89](https://github.com/taptapship/wiredep/blob/de70dc708e47b86c14a4f3cff0267fdeea4c04ad/lib/inject-dependencies.js#L89). When referring to source code, please use the [permanent link](https://help.github.com/articles/getting-permanent-links-to-files/) to the file as what's on `master` is constantly changing.

For now tho, please close this ticket and reopen on [taptapship/wiredep](https://github.com/taptapship/wiredep/issues/new)

**Comment by coreyog** [comment]
So sorry. The bug is related to an older version (0.7.0) in my frustration of hunting down what went wrong, I overlooked that.

**Comment by CWSpear** [comment]
No worries! Thanks for taking the time to report a bug and try to help. If you're still having issues on the latest, let us know (and if the issue is with `wiredep` itself, that other repo is the best place to post those!).
