### ISSUE TITLE
Can grunt-wiredep inject multiple dependencies from single bower package?

### ISSUE THREAD

**Issue by llamaluvr** [stephenplusplus/grunt-wiredep#139]
I'm using the persistence.js bower package. It has several JS files. grunt-wiredep pulls in the persistence.js file already. Is there something I can do to tell it which other files from the package I'd like injected into my index.html?

**Comment by BrianGenisio** [comment]
I have the same question.  I'm trying to bring in [angular-strap](https://github.com/mgcrea/angular-strap/tree/master/dist) which has a "modules" folder.  Wiredep is bringing in the js files properly but I need to include some specific modules from the "modules" folder.  Is there a grunt configuration way of doing this?

**Comment by eddiemonge** [comment]
use the override property in bower.json
