### ISSUE TITLE
Redundancy?

### ISSUE THREAD

**Issue by dderiso** [stephenplusplus/grunt-wiredep#141]
Hi Stephen,

Thanks for developing this awesome package! These appear to point to the same repo, but have different names and versions. Is there a difference or are they redundant? Wiredep looks newer in grunt, is this the package we should use? 

https://www.npmjs.com/package/grunt-bower-install
https://www.npmjs.com/package/grunt-wiredep

Note some devs are confused here: http://stackoverflow.com/questions/18814806/can-bower-automatically-write-script-tags-into-index-html

Thanks!  

Cheers,
Dave

**Comment by CWSpear** [comment]
`grunt-bower-install` is an old, deprecated version. It was renamed `grunt-wiredep` some time back (`wiredep` is the tool it's based on, and `grunt-wiredep` is just a `grunt` wrapper for it).

The `grunt-bower-install` GitHub repo was forward (if you go to https://github.com/stephenplusplus/grunt-bower-install, you'll note you're forwarded to https://github.com/stephenplusplus/grunt-wiredep), but it appears that the same wasn't done for `npm`.

@stephenplusplus do you know if there's a way to forward an `npm` package? I don't think there is, but I do know there is that [deprecate](https://docs.npmjs.com/cli/deprecate) thing that we should maybe use to point people to the new and updated package.

**Comment by stephenplusplus** [comment]
When a user installs `grunt-bower-install`, here's what they get:

```
npm WARN deprecated grunt-bower-install@1.6.0: use grunt-wiredep instead
```

It's not much, but that's how packages look when they're deprecated. We want users to know there's an alternative, but we can't destroy the code their project depends on. If they prefer `grunt-bower-install`, or simply don't need any of the upgrades or re-configurations newer versions of `grunt-wiredep` have made, they don't have to upgrade.

As for the SO issue, it's already cleared up in the comments the project was renamed, and old links redirect to this repo. There's not much left to do, although I added a comment onto my original answer that explains it was renamed.

Thanks for the kind words @dderiso!

**Comment by CWSpear** [comment]
@stephenplusplus maybe add a note and link to https://www.npmjs.com/package/grunt-bower-install? I'm surprised there's nothing else there that says it's deprecated (like a badge `npm` adds on its own when you deprecate).
