### ISSUE TITLE
One strange thing

### ISSUE THREAD

**Issue by huxinmin** [stephenplusplus/grunt-wiredep#145]
![qq 20160111171205](https://cloud.githubusercontent.com/assets/14084481/12229860/84c37986-b886-11e5-8379-8c42b26e4b74.png)
why js has been imported but not ths css?

**Comment by stephenplusplus** [comment]
More details and a test case would be helpful :)

**Comment by huxinmin** [comment]
bower.json
![bower](https://cloud.githubusercontent.com/assets/14084481/12253179/f1f327d0-b918-11e5-8717-cc49ab88f861.png)
gruntfile.js
![gruntfile](https://cloud.githubusercontent.com/assets/14084481/12253182/f1f7157a-b918-11e5-9efb-6838e8318604.png)
index.html
![index](https://cloud.githubusercontent.com/assets/14084481/12253181/f1f4c892-b918-11e5-987c-3c586cd76ccd.png)
package.json
![package](https://cloud.githubusercontent.com/assets/14084481/12253178/f1f3127c-b918-11e5-80d6-c2a103d4138d.png)
these are my seetings and then i run grunt wiredep
![cmd](https://cloud.githubusercontent.com/assets/14084481/12253205/11a8e740-b919-11e5-9c49-15a06ad54034.png)
index.html
![index2](https://cloud.githubusercontent.com/assets/14084481/12253235/5030f32c-b919-11e5-9770-e5bc61d87fe9.png)
and i don not know why it is wrong

**Comment by stephenplusplus** [comment]
https://github.com/stephenplusplus/grunt-wiredep/issues/135 :(
