### ISSUE TITLE
Component is not injecting in .html file

### ISSUE THREAD

**Issue by sajjadROR** [stephenplusplus/grunt-wiredep#146]
![26](https://cloud.githubusercontent.com/assets/8552702/12580351/b2093a40-c450-11e5-9686-6fc10d4ddb37.png)
Here is my code.
        grunt.loadNpmTasks('grunt-wiredep');
         wiredep: {
	      target: {
	        src: 'index.html' // point to your HTML file.
	      }
	    }

and in index.html
< !-- bower:js -->
 < !-- endbower -->

after that i install any library via bower like.
  bower install jquery --save
and then
grunt wiredep

after that i got 
➜  dc-customer-portal-spa git:(master) ✗ grunt wiredep --debug                    
Running "wiredep:target" (wiredep) task
[D] Task source: /var/www/dc-customer-portal-spa/node_modules/grunt-wiredep/tasks/wiredep.js

Done, without errors.

But not included in html file, Kindly guide me.

**Comment by stephenplusplus** [comment]
Could you put together a small test case report or gist including the minimum required files to reproduce?

**Comment by sajjadROR** [comment]
https://gist.github.com/sajjadROR/ff0e472b02f8dd7e486f

**Comment by stephenplusplus** [comment]
Thanks, but please include all files so that I can clone, install, and reproduce. bower.json, package.json, etc

**Comment by sajjadROR** [comment]
Actually that is in my project. You can check again. I think you will get an idea
https://gist.github.com/sajjadROR/ff0e472b02f8dd7e486f

**Comment by sajjadROR** [comment]
and please look at this https://cloud.githubusercontent.com/assets/8552702/12580351/b2093a40-c450-11e5-9686-6fc10d4ddb37.png

**Comment by stephenplusplus** [comment]
Thanks! It looks like jquery isn't saved to your bower.json. Try running `bower install --save jquery`

**Comment by sajjadROR** [comment]
No - i just removed when i pasted here.
i was something like that
"dependencies": {
    "jquery": "~2.2.0"
  }
i tried again but ... no success

**Comment by sajjadROR** [comment]
@stephenplusplus  Thank you so much - Actually there was problem of path :+1: 
Thanks for you time

**Comment by stephenplusplus** [comment]
Oh great, glad you caught the problem!

**Comment by sajjadROR** [comment]
@stephenplusplus  can you give me a favour.?
when component is added in index.html. Can we redo or remove the <script src=""></script>.
If yes please guide. It will be last question.

**Comment by stephenplusplus** [comment]
Check out the wiredep configuration docs: https://github.com/taptapship/wiredep#configuration

If you find an option there that you want to use, you can set it in the Gruntfile configuration like this:

```js
grunt.initConfig({
    wiredep: {
      target: {
        src: 'index.html',
        options: {
          // options go here
        }
      }
    }
  });
```

I think you might want `ignorePath`. From the docs linked above:

> **ignorePath**: /string or regexp to ignore from the injected filepath/

So that means if you're getting:

```html
<!-- bower:js -->
<script src="../some/path/jquery/jquery.js"></script>
<!-- endbower -->
```

If you set `ignorePath` to `../some/path`, you'll get:

```html
<!-- bower:js -->
<script src="jquery/jquery.js"></script>
<!-- endbower -->
```

**Comment by sajjadROR** [comment]
Thanks

For example,
When i will run grunt wiredep, it will add <script src="../some/path/jquery/jquery.js"></script> in my index.html file.

And after some time i uninstall jquery ( bower uninstall jquery). This will remove jquery file from bower_components.
I want to ask from you, when there will be no file is there any way or method which is used for removing this line <script src="../some/path/jquery/jquery.js"></script> from index.html.

Are you getting my point.? @stephenplusplus

**Comment by stephenplusplus** [comment]
wiredep will always use your bower.json as the source of truth. So when you install a package, you have to persist your changes by always using --save.

**Comment by sajjadROR** [comment]
If i don't want to include file from bower_component folder. Is there any way to give other destination path.
for example if i have a file testAlert.js in /home/user/Desktop/testAlert.js
and i want to inject by using grunt wiredep - is it possible.?
