### ISSUE TITLE
ignored dependencies in .bowerrc

### ISSUE THREAD

**Issue by pangwa** [stephenplusplus/grunt-wiredep#149]
in bowerrc, we can config to ignore some dependencies, e.g. not install momentjs package.

> $.bowerrc
> {
>   "ignoredDependencies": [
>     "momentjs"
>   ]
> }

grunt wiredep will complain it can't finds momentjs package and gives up due to an warning.

> Running "wiredep:app" (wiredep) task
> Warning: Error: momentjs is not installed. Try running `bower install` or remove the component from your bower.json file. Used --force, continuing.
>

**Comment by eddiemonge** [comment]
this should be opened on wiredep as it does the actual work
