### ISSUE TITLE
Publish 4.0.0 to npm?

### ISSUE THREAD

**Issue by jo-flynn** [stephenplusplus/grunt-wiredep#153]
Attempting to install 4.0.0 from npm results in this error:

```
npm ERR! No compatible version found: grunt-wiredep@~4.0.0
npm ERR! Valid install targets:
npm ERR! 3.0.1, 3.0.0, 2.0.0, 1.9.0, 1.8.0, 1.7.1, 1.7.0
```

It appears 4.0.0 hasn't been published to npm.

**Comment by jo-flynn** [comment]
Disregard, I'm an idiot.

**Comment by stephenplusplus** [comment]
Haha, maybe you're just stopping by from the future and this issue will be relevant whenever 4.0 comes around. Mental reminder to self: don't forget to publish 4.0.0 to npm.

**Comment by jo-flynn** [comment]
Haha, no problem ;) I got this & wiredep itself mixed up and thought this wasn't published.
