### ISSUE TITLE
CSS reference not loading

### ISSUE THREAD

**Issue by cowglow** [stephenplusplus/grunt-wiredep#154]
```
"dependencies": {
    "angular": "1.2.16",
    "json3": "~3.3.1",
    "es5-shim": "~3.1.0",
    "bootstrap": "^3.3.7",
  },
```

All the JS files load but not the CSS ref for Bootstrap.

**Comment by muskiii** [comment]
same here , only some css apears bootstrap.js apears but bootstrap.css dose not

**Comment by mkerr** [comment]
Having the same issue. Any word on this?

**Comment by cowglow** [comment]
Probably gonna have to do it manually.
