### ISSUE TITLE
Can it be used for styles?

### ISSUE THREAD

**Issue by ekkis** [stephenplusplus/grunt-wiredep#157]
a lot of bower packages comes with their own stylesheets, can this module be used to include them? if not, is there another module I should be using?

seems to me it wouldn't be that different to pick up css files and could be integrated into this module...

**Comment by marcoooo** [comment]
css files are inserted with this tag in your html files (defined in src options) : 
```html
<!-- bower:css -->
<!-- endbower -->
```

**Comment by ekkis** [comment]
yes, I figured it out quite a while back.  thanks for responding
