### ISSUE TITLE
bower-install updates index.html but not karma.conf.js

### ISSUE THREAD

**Issue by snicolai** [stephenplusplus/grunt-wiredep#35]
I like that I can run

``` sh
$ bower install -S angular-bootstrap
$ grunt bower-install
```

and index.html is updated with the new bower component.  I would like karma.conf.js to be updated as well, so that my tests are ready to use the new component.

I don't know if this should be added to bower-install, or should be a separate task, but I would like this to be automatic as well.

I'm using yeoman with generator-angular to build my Gruntfile.js.  If a new task is created for this, then that generator will need to be updated.

See https://github.com/yeoman/generator-angular/issues/534

**Comment by jdmagic21** [comment]
@stephenplusplus What is with the yoeman stuff?

**Comment by ktschmincke** [comment]
@stephenplusplus I tried your solution but I'm getting this error. Any thoughts?

    $ grunt wiredep:test
    Running "wiredep:test" (wiredep) task
    Warning: reference.replace is not a function Use --force to continue.

    Aborted due to warnings.
