### ISSUE TITLE
Cannot read property 'main' of undefined Use

### ISSUE THREAD

**Issue by margarito** [stephenplusplus/grunt-wiredep#36]
Hey!
My 'bower-install' instructions in my Gruntfile breaks grunt when is called and let this message:

```
Cannot read property 'main' of undefined Use
```

This is my grunt config for "bower-install":

```
'bower-install': {
    target: {
        src: ['app/index.html'],
        cwd: ' ',
        ignoredPath: ' ',
        exclude: [],
        fileTypes: {}
    }
}
```

Thank you

**Comment by blacknight811** [comment]
Same here I had this problem today. A quick ```bower install``` took care of it.

**Comment by elise-fastpay** [comment]
In some instances, it may be necessary to run `bower cache clean` [http://bower.io/docs/api/#cache](url)
