### ISSUE TITLE
Cannot read property 'main' of undefined

### ISSUE THREAD

**Issue by lukaszklis** [stephenplusplus/grunt-wiredep#79]
Hey, I've just installed your grunt task and integrated it with my Gruntfile. After adding dependencies to `bower.json` and saving the file, task has been triggered, however it's not installing the dependencies. I got the following warning:

```
Running "watch" task
Waiting...
>> File "bower.json" changed.
Running "wiredep:app" (wiredep) task
Warning: Cannot read property 'main' of undefined Use --force to continue.

Aborted due to warnings.
```

I've checked all dependencies which I'm using in the project and theirs' `bower.json` contains `main` property with path to the existing file.

Any ideas what could go wrong?

Bower's version: 1.3.3
grunt-wiredep's version: 1.7.0

**Comment by earthquakesan** [comment]
That means that there is a missing package from bower.json. Needs a better message.

I've just removed a package with bower uninstall, but forgot to remove it from bower.json and got this error. After removing from bower.json, everything works fine.

**Comment by prdonahue** [comment]
@earthquakesan to whom are you replying? My issue was the fact it didn't recognize `exportsOverride` though admittedly I somewhat hijacked the thread.

**Comment by earthquakesan** [comment]
@prdonahue I think, that would be general suggestion for improving the package. Because the issue occurs basically when bower.json and actual bower_components folder are not in sync and there is a necessity either to remove entries from bower.json or run bower install.
