### ISSUE TITLE
Cannot npm install - TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by jlnslv** [stephenplusplus/grunt-wiredep#9]
Hey there,

I've just tried to install your awesome grunt plugin.

But I always get the following error:

```
verbose from cache /Users/jsilva/Desktop/boilerplate/package.json
error TypeError: Object.keys called on non-object
error     at Function.keys (native)
error     at /usr/local/lib/node_modules/npm/lib/build.js:111:18
error     at process._tickCallback (node.js:415:13)
error If you need help, you may report this log at:
error     <http://github.com/isaacs/npm/issues>
error or email it to:
error     <npm-@googlegroups.com>
error System Darwin 12.3.0
error command "node" "/usr/local/bin/npm" "install" "grunt-bower-install" "--save-dev"
error cwd /Users/jsilva/Desktop/boilerplate
error node -v v0.10.5
error npm -v 1.2.21
error type called_on_non_object
verbose exit [ 1, true ]
```

The full log is here http://jlnslv.me/TB0B

Do you know where the issue is? I googled a little but I could pin down where the bug is.

I'm running node 0.10.5 on Mac OS X 10.8.3

Julien

**Comment by nda888** [comment]
Hi stephenplusplus,

I got same problem

Here's my package.json:
{
  "name": "edx-analytics-dashboard",
  "repository": {
    "type": "git",
    "url": "git://github.com/edx/edx-analytics-dashboard"
  },
  "dependencies": {},
  "devDependencies": {
    "browser-sync": "^1.1.2",
    "edx-custom-a11y-rules": "edx/edx-custom-a11y-rules#ff77f203ef5d9534c6200cc141e9d150155d0e12",
    "gulp": "^3.8.8",
    "gulp-jscs": "^1.3.0",
    "gulp-jshint": "^1.6.3",
    "gulp-karma": "0.0.4",
    "jscs": "^1.10.0",
    "karma": "^0.12.16",
    "karma-coverage": "^0.2.6",
    "karma-jasmine": "^0.1.5",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-requirejs": "^0.2.2",
    "karma-sinon": "^1.0.3",
    "phantomjs": "^1.9.11",
    "sinon": "^1.10.3"
  }
}

Im deploying Insight Analystic OpenEDX but failed this step
May you help
Thanks

An,
